load("@rules_haskell//haskell:defs.bzl", "haskell_binary")

haskell_binary(
    name = "generate",
    srcs = ["generate.hs"],
    tags = [
        "haskell",
        "no-cross",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hs-happy-arbitrary",
        "//hs-happy-arbitrary:ast",
        "//hs-happy-arbitrary:lexer",
        "//hs-happy-arbitrary:parser",
        "//third_party/haskell:QuickCheck",
        "//third_party/haskell:base",
        "//third_party/haskell:bytestring",
        "//third_party/haskell:containers",
        "//third_party/haskell:optparse-applicative",
        "//third_party/haskell:text",
    ],
)
